config/routes.rb
Rails.application.routes.draw do
  get '/sign_out_user', to: 'users#sign_out_user', as: 'sign_out_user'
  get '/public_recipes', to: 'recipes#public_recipes', as: 'public_recipes'

  devise_for :users
  devise_scope :user do
    authenticated :user do
      root to: 'home#index', as: :authenticated_root
    end

    unauthenticated do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :recipes do
    member do
      get 'add_ingredient', to: 'recipes#add_ingredient'
      post 'create_ingredient', to: 'recipes#create_ingredient'
      get 'generate_shopping_list', to: 'recipes#generate_shopping_list'
    end
    resources :ingredients
  end
  
  resources :foods, only: [:new, :create, :index, :destroy]

  post 'create_recipe', to: 'home#create_recipe'
  post 'create_food', to: 'home#create_food'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  has_many :recipe_foods, dependent: :destroy
  has_many :recipes, through: :recipe_foods
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  def value
    food.unit_price * quantity
  end

  validates :quantity, numericality: { greater_than: 0 }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods
  has_many :ingredients, dependent: :destroy

  validates :title, presence: true
  validates :description, presence: true
  validates :preparation_time, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :cooking_time, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/shopping_list.rb
class ShoppingList
  attr_reader :recipe

  def initialize(recipe)
    @recipe = recipe
  end

  def calculate_total_value
    recipe.ingredients.map(&:value).sum
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, presence: true

  has_many :recipes
  has_many :foods
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = Food.all
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)

    if @food.save
      redirect_to foods_path, notice: 'Food was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    redirect_to foods_path, notice: 'Food was successfully deleted.'
  end

  private

  def set_food
    @food = Food.find(params[:id])
  end

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :unit_price)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @recipes = Recipe.all
    @new_recipe = Recipe.new
    @food = Food.new
    @foods = Food.all
  end

  def create_recipe
    @new_recipe = Recipe.new(recipe_params)
    @new_recipe.user = current_user
    if @new_recipe.save
      redirect_to authenticated_root_path, notice: 'Recipe was successfully created.'
    else
      render :index
    end
  end

  def create_food
    @food = Food.new(food_params)

    if @food.save
      redirect_to authenticated_root_path, notice: 'Food was successfully created.'
    else
      render :index
    end
  end

  def recipe_params
    params.require(:recipe).permit(:title, :description, :preparation_time, :cooking_time, :public)
  end

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :unit_price)
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_recipe
  before_action :set_ingredient, only: [:destroy]

  def new
    @ingredient = Ingredient.new
    @foods = Food.all
  end

  def create
    @ingredient = @recipe.ingredients.build(ingredient_params)
    if @ingredient.save
      redirect_to recipe_path(@recipe), notice: 'Ingredient added successfully.'
    else
      render :new
    end
  end

  def destroy
    @recipe = Recipe.find(params[:recipe_id])
    @ingredient = @recipe.ingredients.find(params[:id])
    @ingredient.destroy

    respond_to do |format|
      format.html { redirect_to @recipe, notice: 'Ingredient was successfully removed.' }
      format.js
    end
  end

  def edit
    @ingredient = @recipe.ingredients.find(params[:id])
    @foods = Food.all
  end

  def update
    @ingredient = @recipe.ingredients.find(params[:id])
    if @ingredient.update(ingredient_params)
      redirect_to @recipe, notice: 'Ingredient was successfully updated.'
    else
      render :edit
    end
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:recipe_id])
  end

  def set_ingredient
    @ingredient = @recipe.ingredients.find(params[:id])
  end

  def ingredient_params
    params.require(:ingredient).permit(:food_id, :quantity)
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @public_recipes = Recipe.where(public: true).order(created_at: :desc)
  end
end

app/controllers/public_recipes_helper.rb
module PublicRecipesHelper
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  helper RecipesHelper
  def index
    @recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)

    if @recipe.save
      redirect_to recipes_path, notice: 'Recipe was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    redirect_to recipes_path, notice: 'Recipe was successfully destroyed.'
  end

  def show
    @recipe = Recipe.find(params[:id])
    @ingredients = @recipe.ingredients
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      respond_to do |format|
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      end
    else
      respond_to do |format|
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def add_ingredient
    @recipe = Recipe.find(params[:id])
    @ingredient = Ingredient.new
    @foods = Food.all
  end

  def create_ingredient
    @recipe = Recipe.find(params[:id])
    @ingredient = @recipe.ingredients.build(ingredient_params)

    if @ingredient.save
      redirect_to @recipe, notice: 'Ingredient added successfully.'
    else
      render :add_ingredient
    end
  end

  def generate_shopping_list
    @recipe = Recipe.find(params[:id])
  end

  skip_before_action :authenticate_user!, only: [:public_recipes]
  def public_recipes
    @public_recipes = Recipe.where(public: true).includes(:user, ingredients: :food)
  end

  private

  def recipe_params
    params.require(:recipe).permit(:title, :description, :preparation_time, :cooking_time, :public)
  end

  def ingredient_params
    params.require(:ingredient).permit(:food_id, :quantity)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def sign_out_user
    sign_out(current_user)
    redirect_to new_user_session_path, notice: 'Signed out successfully'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
  def calculate_total_price(recipe)
    recipe.ingredients.map(&:value).sum
  end

  def calculate_total_value(recipe)
    total_value = recipe.ingredients.sum { |ingredient| ingredient.food.price * ingredient.quantity }
    number_to_currency(total_value, precision: 2)
  end
end

app/views/foods/index.html.erb
<div class="container mt-5">
  <h1>Food List</h1>
  <table class="table mt-3">
    <thead>
      <tr>
        <th>Food</th>
        <th>Measurement Unit</th>
        <th>Unit Price</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% if @foods.present? %>
        <% @foods.each do |food| %>
          <tr>
            <td><%= food.name %></td>
            <td><%= food.measurement_unit %></td>
            <td>$<%= food.unit_price %></td>
            <td>
              <%= button_to "Remove", food, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-sm" %>
            </td>
          </tr>
        <% end %>
      <% else %>
        <tr>
          <td colspan="4">
            <div class="alert alert-warning mt-3" role="alert">
              No foods available.
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/foods/new.html.erb
<h1 class="title is-flex is-justify-content-center">Add New Food</h1>

<div class="container" style="width: 50%;">
  <%= form_with model: @food, url: foods_path, method: :post, local: true do |form| %>
    <div class="mb-3">
      <%= form.label :name, class: "label" %>
      <%= form.text_field :name, class: "input" %>
    </div>

    <div class="mb-3">
      <%= form.label :measurement_unit, class: "label" %>
      <%= form.text_field :measurement_unit, class: "input" %>
    </div>

    <div class="mb-3">
      <%= form.label :price, class: "label" %>
      <%= form.number_field :price, class: "input", step: 1 %>
    </div>

    <div class="mb-3">
      <%= form.label :quantity, class: "label" %>
      <%= form.number_field :quantity, class: "input", step: 1 %>
    </div>

    <div>
      <%= form.submit class: "button is-info" %>
    </div>
  <% end %>
</div>

app/views/home/_create_food_form.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <h3 class="mb-4">Add your food</h3>

      <%= form_for new_food, url: create_food_path, method: :post, html: { class: 'mb-4' } do |f| %>
        <div class="mb-3">
          <%= f.label :name, class: 'form-label' %><br>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="mb-3">
          <%= f.label :measurement_unit, class: 'form-label' %><br>
          <%= f.select :measurement_unit, ['Unit', 'Kg', 'Liter'], { prompt: 'Select Unit' }, class: 'form-select' %>
        </div>
        <div class="mb-3">
          <%= f.label :unit_price, class: 'form-label' %><br>
          <%= f.text_field :unit_price, class: 'form-control' %>
        </div>
        <div class="text-center">
          <%= f.submit "Add Food", class: 'btn btn-success btn-lg' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/home/_create_recipe_form.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <h3 class="mb-4">Add your recipe</h3>
      <%= form_for @new_recipe, url: create_recipe_path, method: :post, html: { class: 'mb-4' } do |f| %>
        <div class="mb-3">
          <%= f.label :title, class: 'form-label' %>
          <%= f.text_field :title, class: 'form-control' %>
        </div>
        <p>
          <%= f.label :preparation_time, class: 'form-label' %>
          <br/>
          <%= f.number_field :preparation_time, class: 'form-control' %>
        </p>
        <p>
          <%= f.label :cooking_time, class: 'form-label' %>
          <br/>
          <%= f.number_field :cooking_time, class: 'form-control' %>
        </p>
        <p>
          <%= f.label :public %>
          <%= f.check_box :public %>
        </p>
        <div class="mb-3">
          <%= f.label :description, class: 'form-label' %>
          <%= f.text_area :description, class: 'form-control' %>
        </div>
        <div class="text-center">
          <%= f.submit "Add Recipe", class: 'btn btn-primary btn-lg' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="container mt-5">
  <h1 class="display-3">Welcome to the Dashboard</h1>

  <div class="row mt-5">
    <div class="col-md-6">
      <%= link_to "Recipes", recipes_path, class: "btn btn-primary btn-lg btn-block" %>
    </div>
    <div class="col-md-6">
      <%= link_to "Foods", foods_path, class: "btn btn-success btn-lg btn-block" %>
    </div>
  </div>

  <div class="row mt-5">
    <div class="col-md-6">
      <%= render 'create_recipe_form' %>
    </div>
    <div class="col-md-6">
      <%= render 'create_food_form', new_food: @food %>
    </div>
  </div>
</div>

app/views/ingredients/_form.html.erb
<%= form_with(model: [@recipe, ingredient], local: true) do |form| %>
  <%= form.label :food_id %>
  <%= form.select :food_id, options_for_select(foods.map { |food| [food.name, food.id] }), {}, class: 'form-control' %>

  <%= form.label :quantity %>
  <%= form.number_field :quantity, class: 'form-control' %>

  <%= form.submit 'Save', class: 'btn btn-primary' %>
<% end %>

app/views/ingredients/_ingredient.html.erb
<%= content_tag :tr, render(partial: 'ingredients/ingredient', locals: { ingredient: ingredient }) %>

app/views/ingredients/destroy.js.erb
$('#ingredient_<%= @ingredient.id %>').remove();

app/views/ingredients/edit.html.erb
<%= render 'form', ingredient: @ingredient, foods: @foods %>

app/views/ingredients/new.html.erb
<%= form_with(model: [@recipe, @ingredient], url: recipe_ingredients_path(@recipe)) do |form| %>
  <%= form.label :food_id %>
  <%= form.select :food_id, options_for_select(@foods.map { |food| [food.name, food.id] }), {}, class: 'form-control' %>

  <%= form.label :quantity %>
  <%= form.number_field :quantity, class: 'form-control' %>

  <%= form.submit 'Add Ingredient', class: 'btn btn-primary' %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar has-background-info mb-2 p-3" role="navigation" aria-label="main navigation">
  <div class="navbar-menu">
    <div class="navbar-start">
      <% if current_user %>
        <h1 class="mr-6"><strong class="has-text-white">Welcome <%= current_user.name %></strong></h1>
        <%= link_to "Food", foods_path, class: "has-text-white px-2" %>
        <%= link_to "Recipe", recipes_path, class: "has-text-white px-2" %>  
        <%= link_to "Public Recipe", public_recipes_path, class: "has-text-white px-2" %>
          <%= link_to "General Shoping List", users_general_shopping_list_path, class: "has-text-white px-2" %>
      <% end %>
    </div>
  </div>

  <div class="navbar-end">
    <%= link_to "Sign Out", destroy_user_session_path, method: :delete, data: { "turbo-method": :delete }, class: "button is-small is-dark" %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipe App</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </head>

  
  <body>    
    <% if user_signed_in? %>
      <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <%= link_to 'Home', authenticated_root_path, class:"navbar-brand" %>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                  <%= link_to 'Add Recipe', authenticated_root_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                  <%= link_to 'Add Food', authenticated_root_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                  <%= link_to 'Recipes List', recipes_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                  <%= link_to 'Foods List', foods_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                  <%= link_to 'Public Recipes', public_recipes_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                  <%= link_to 'Log-out', destroy_user_session_path, method: :delete, 'data-turbo-method': :delete, class: "nav-link" %>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    <% else %>
      <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                  <%= link_to 'Sign-in', new_user_session_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                  <%= link_to 'Sign-up', new_user_registration_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                  <%= link_to 'Public Recipes', public_recipes_path, class: "nav-link" %>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    <% end %>
    
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/public_recipes/index.html.erb
<h1 class="title is-flex is-justify-content-center">List of Public Recipes</h1>

<div class="container" style="width: 50%;">
  <% @public_recipes.each do |public_recipe| %>   
    <div class="is-flex mt-4 mb-4 column has-background-light radius-all shadow-gray">
      <div>
        <%= link_to public_recipe.name, recipe_path(public_recipe), class: "title is-5 has-text-grey is-info-dark" %>
        <p class="mt-3">By: <%= public_recipe.user.name %></p>
      </div>
      <div class="ml-5">
        <p>Total food items: <%= public_recipe.foods.count %></p>
        <p>Total price: <%= number_to_currency(public_recipe.foods.sum(:price))%></p>
      </div>
    </div>
  <% end %>
</div>

app/views/recipe_foods/new.html.erb
<div class="is-flex is-justify-content-center">
  <h1 class="title" style="margin-left: 20px;">Add new Ingredient to <%= @recipe.name %></h1>
  <%= form_with model: [@recipe, @recipe_food], html: { class: "form" } do |form| %>
    <% if @recipe_food.errors.any? %>
      <div class="error-messages">
        <% @recipe_food.errors.full_messages.each do |message| %>
          <div><%= message.inspect %></div>
        <% end %>
      </div>
    <% end %>
    <%= form.hidden_field :recipe_id, value: @recipe.id %>

    <div class="field">
      <%= form.label :food_name, class: "label" %>
      <div class="control">
        <%= form.collection_select :food_id, @foods, :id, :name, { prompt: "Select food item" }, class: "select" %>
      </div>
    </div>

    <div class="field">
      <%= form.label :ingredient_quantity, class: "label" %>
      <div class="control">
        <%= form.text_field :quantity, class: "input" %>
      </div>
    </div>

    <div class="field">
      <div class="control">
        <%= form.submit 'Add Ingredient', class: "button is-primary" %>
      </div>
    </div>
  <% end %>
  </div>

app/views/recipes/add_ingredient.html.erb
<div class="container">
  <h2>Add Ingredient to <%= @recipe.title %></h2>
  
  <%= form_with(model: [@recipe, Ingredient.new], url: create_ingredient_recipe_path(@recipe), local: true) do |form| %>
    <%= form.label :food_id %>
    <%= form.select :food_id, options_for_select(@foods.map { |food| [food.name, food.id] }), {}, class: 'form-control' %>
  
    <%= form.label :quantity %>
    <%= form.number_field :quantity, class: 'form-control' %>
  
    <%= form.submit 'Add Ingredient', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/recipes/create_ingredient.html.erb
<h2>Ingredient Added Successfully!</h2>

<p>Your ingredient has been added to <%= @recipe.title %>.</p>

<%= link_to 'Back to Recipe', recipe_path(@recipe), class: 'btn btn-primary' %>

app/views/recipes/generate_shopping_list.html.erb
<div class="container">
  <% shopping_list = ShoppingList.new(@recipe) %>
  
  <h1>Shopping List for <%= @recipe.title %></h1>
  
  <p>Amount of food items to buy:
    <%= @recipe.ingredients.count %>
  </p>
  <p>Total value of food needed:
    <%= number_to_currency(shopping_list.calculate_total_value, precision: 2) %>
  </p>
  
  <table class="table">
    <thead>
      <tr>
        <th>Food Name</th>
        <th>Quantity</th>
        <th>Price</th>
      </tr>
    </thead>
    <tbody>
      <% @recipe.ingredients.each do |ingredient| %>
        <tr>
          <td><%= ingredient.food.name %></td>
          <td><%= "#{ingredient.quantity} #{ingredient.food.measurement_unit}" %></td>
          <td><%= "$#{ingredient.value}" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/recipes/index.html.erb
<div class="container mt-5">
  <h1>Recipes List</h1>

<% if @recipes.present? %>
  <div class="d-flex flex-column gap-2">
    <% @recipes.each do |recipe| %>
      <section class="d-flex justify-content-between align-items-center border border-dark flex-item p-3">
        <div>
          <h2><%= recipe.title %></h2>
          <div class="d-flex">
            <%= link_to "More info", recipe_path(recipe), class:"btn btn-info" %>
            <%= button_to "Remove", recipe, method: :delete, data: { confirm: "Are you sure?" }, class:"btn btn-danger" %>
          </div>
        </div>
        <p class="flex-item text-left">
          <%= recipe.description %>
        </p>
      </section>
    <% end %>
  </div>
<% else %>
  <div class="alert alert-warning mt-3" role="alert">No Recipes available.</div>
<% end %>
</div>

app/views/recipes/new.html.erb
<h1 class="title is-flex is-justify-content-center">New Recipe</h1>

<div class="container" style="width: 50%;">
  <%= form_with model: @recipe do |f| %>

    <% if @recipe.errors.any? %>
      <div>
        <% @recipe.errors.full_messages.each do |message| %>
          <div><%= message.inspect %></div>
        <% end %>
      </div>
    <% end %>

    <div class="mb-3">
      <%= f.label :name, class: "label" %>
      <%= f.text_field :name, required: true, class: "input" %>
    </div>

    <div class="mb-3">
      <%= f.label :preparation_time, "Preparation Time (hours)", class: "label" %>
      <%= f.number_field :preparation_time, class: "input", step: 1, required: true %>
    </div>

    <div class="mb-3">
      <%= f.label :cooking_time, "Cooking Time (hours)", class: "label" %>
      <%= f.number_field :cooking_time, class: "input", step: 1, required: true %>
    </div>

    <div class="mb-3">
      <%= f.label :description, class: "label" %>
      <%= f.text_area :description, class: "input", required: true %>
    </div>

    <div class="mb-3">
      <%= f.label :public, class: "label" %>
      <%= f.label :public, "Yes" %>
      <%= f.radio_button :public, true, class: "mr-4" %>
      <%= f.label :public, "No" %>
      <%= f.radio_button :public, false %>
    </div>

    <div>
      <%= f.submit "Create Recipe", class: "button is-info" %>
    </div>

  <% end %>
</div>

app/views/recipes/show.html.erb
<div class="container">
  <h1 class="text-center text-capitalize"><%= @recipe.title %></h1>
  
  
  <div class='d-flex justify-content-between'>
    <p>Preparation Time: <%= @recipe.preparation_time %> hours</p>
    <div class="form-check form-switch">
      <label class="form-check-label" for="flexSwitchCheckChecked">Public:</label>
      <input class="form-check-input" type="checkbox" id="flexSwitchCheckChecked" <%= @recipe.public ? 'checked' : '' %>>
    </div>
  </div>
  
  <p>Cooking Time <%= @recipe.cooking_time %> hours</p>
  <p>Description: <%= @recipe.description %></p>
  
  <div class="d-flex justify-content-between">
    <%= link_to 'Generate Shopping List', generate_shopping_list_recipe_path(@recipe), class: 'btn btn-primary' %>
    <%= link_to 'Add Ingredient', add_ingredient_recipe_path(@recipe), class: 'btn btn-primary' %>
  </div>
  
  <hr/>
  <table class="table">
    <thead>
      <tr>
        <th>Food Name</th>
        <th>Quantity</th>
        <th>Value</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @recipe.ingredients.each do |ingredient| %>
        <tr>
          <td><%= ingredient.food.name %></td>
          <td><%= "#{ingredient.quantity} #{ingredient.food.measurement_unit}" %></td>
          <td><%= "$#{ingredient.value}" %></td>
          <td class="d-flex">
            <%= button_to 'Modify', edit_recipe_ingredient_path(@recipe, ingredient), method: :get, class: 'btn btn-warning' %>
            <%= button_to 'Remove', [@recipe, ingredient], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<script>
  $(document).ready(function() {
    $('#flexSwitchCheckChecked').change(function() {
      var publicStatus = $(this).is(':checked');
      var csrfToken = $('meta[name="csrf-token"]').attr('content');
      
      $.ajax({
        type: 'PATCH',
        url: '<%= recipe_path(@recipe) %>',
        data: { recipe: { public: publicStatus } },
        headers: { 'X-CSRF-Token': csrfToken },
        success: function(data) {
          console.log('Recipe public status updated successfully');
        },
        error: function(xhr, status, error) {
          console.error('Error updating recipe public status:', error);
        }
      });
    });
  });
</script>